# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  BUILD_NUMBER: ${{ github.run_number }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Create Deployment Bundle
      run: |
          mkdir -p deployment/target
          cp target/account-0.0.1-SNAPSHOT.jar deployment/target/
          zip -r deployment-$BUILD_NUMBER.zip deployment
    - name: Publish Deployment Artifact
      uses: actions/upload-artifact@v4
      with:
          name: deployment-artifact
          path: ${{github.workspace}}/deployment-${{ github.run_number }}.zip




